server:
  port: 8180

spring:
  application:
    name: workflow-camunda-service
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda7
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update   # create | create-drop | update | validate | none
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
    sql:
      init:
        mode: always   # nếu muốn chạy schema.sql/data.sql

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      first-name: Admin
    filter:
      create: All Tasks          # Tạo filter mặc định trên Tasklist
    database:
      schema-update: true
    datasource:
      url: jdbc:postgresql://localhost:5432/camunda7
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver
    history-level: audit         # none | activity | audit | full
    auto-deployment-enabled: true  # Tự deploy BPMN trong resources/
    webapp:
      application-path: /camunda # URL truy cập Cockpit/Tasklist