server:
  port: 8180

spring:
  application:
    name: workflow-camunda-service
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda7
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update   # create | create-drop | update | validate | none
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
    sql:
      init:
        mode: always   # nếu muốn chạy schema.sql/data.sql

camunda:
  bpm:
    database:
      schema-update: true
    datasource:
      url: jdbc:postgresql://localhost:5432/camunda7
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver
    admin-user:
      id: admin
      password: admin
      first-name: Admin
    filter:
      create: All Tasks          # Tạo filter mặc định trên Tasklist
    history-level: audit         # none | activity | audit | full
    auto-deployment-enabled: true  # Tự deploy BPMN trong resources/
    webapp:
      application-path: /camunda # URL truy cập Cockpit/Tasklist
    generic-properties:
      properties:
        historyTimeToLive: P90D     # History time to live for batch operations (default is 30 days)
        batchOperationHistoryTimeToLive: P90D # History time to live for batch operations (default is 30 days)
        historyCleanupBatchWindowStartTime: 02:00:00 # Time when cleanup batch job is started (default is 02:00:00)
        historyCleanupBatchWindowEndTime: 06:00:00   # Time when cleanup batch job is stopped (default is 06:00:00)
        historyCleanupStrategy: "removalTimeBased" # Strategy for history cleanup (default is "removalTime")
